server:
  servlet:
    context-path: /accounts
  port: 8080
spring:
  application:
    name: accounts-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB_NAME}
javers:
  mappingStyle: FIELD
  algorithm: SIMPLE
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true
  packagesToScan:
  auditableAspectEnabled: true
  springDataAuditableRepositoryAspectEnabled: true
  usePrimitiveDefaults: true
  prettyPrintDateFormats:
    localDateTime: 'dd MMM yyyy, HH:mm:ss'
    zonedDateTime: 'dd MMM yyyy, HH:mm:ssZ'
    localDate: 'dd MMM yyyy'
    localTime: 'HH:mm:ss'
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

urls:
  frontendUrl: ${FRONTEND_CLIENT_URL}

client-urls:
  employeeService: ${EMPLOYEE_SERVICE_BASE_URL}/employees
  notificationService: ${NOTIFICATIONS_SERVICE_BASE_URL}/notifications
  fileService: ${FILE_SERVICE_BASE_URL}/files

authentication:
  clientId: ${GOOGLE_CLIENT_ID}
  tokenUri: https://www.googleapis.com/oauth2/v3/tokeninfo

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml

jwt:
  secret: ${JWT_SECRET_KEY}