package com.beeja.api.accounts.enums;

public enum FeatureToggles {
  EMPLOYEE_MANAGEMENT,
  DOCUMENT_MANAGEMENT,
  LOAN_MANAGEMENT,
  KYC_MANAGEMENT,
  INVENTORY_MANAGEMENT,
  BULK_PAY_SLIPS,
  EXPENSE_MANAGEMENT,
  ORGANIZATION_SETTINGS,
  ORGANIZATION_SETTINGS_PROFILE,
  ORGANIZATION_SETTINGS_DATE_CURRENCY,
  ORGANIZATION_SETTINGS_THEMES,
  ORGANIZATION_SETTINGS_FONT_NAME,
  ORGANIZATION_SETTINGS_FONT_SIZE,
  ORGANIZATION_SETTINGS_ROLES_AND_PERMISSIONS
}
