name: Run JUnit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  junit-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      run: ./gradlew dependencies

    - name: Run Tests
      run: ./gradlew test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: build/test-results/test/
