name: Test Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Spotless Apply
      run: ./gradlew spotlessApply

    - name: Run Checkstyle
      run: ./gradlew checkstyleMain

    