name: Build and Scan docker image with Trivy

on:
  pull_request:
    branches:
      - main
      - PS-87-CI/CD

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker Image with Jib
        run: ./gradlew jibDockerBuild -Djib.to.image=my-app:1.0
        env:
          DOCKER_BUILDKIT: 1

      - name: Trivy Image Scanning for Vulnarability
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-app:1.0
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # - name: Setup Trivy
      #   uses: aquasecurity/trivy-action@master

      # - name: Scan Docker Image
      #   run: trivy image --scanners vuln,misconfig --severity HIGH,CRITICAL my-app:${{ github.sha }}